import Foundation

private let profileTools = ["codex", "claude", "cursor", "windsurf", "opencode"]
private let generatedPrefix = "Generated by Skill Reader profile"

private struct ProfileManifest: Codable {
    var profile_name: String
    var tool: String
    var generated_paths: [String]
    var managed_files: [String]
}

enum ProfileManager {
    static func appHome() -> URL {
        let env = ProcessInfo.processInfo.environment["SKILL_READER_HOME"] ?? "~/.skill-reader"
        let expanded = (env as NSString).expandingTildeInPath
        return URL(fileURLWithPath: expanded, isDirectory: true)
    }

    static func profilesRoot() -> URL { appHome().appendingPathComponent("profiles", isDirectory: true) }
    static func libraryRoot() -> URL { appHome().appendingPathComponent("library", isDirectory: true) }

    static func ensureStorage() throws {
        let fm = FileManager.default
        for url in [
            appHome(),
            profilesRoot(),
            libraryRoot().appendingPathComponent("skills", isDirectory: true),
            libraryRoot().appendingPathComponent("rules", isDirectory: true),
            libraryRoot().appendingPathComponent("agents", isDirectory: true),
        ] {
            try fm.createDirectory(at: url, withIntermediateDirectories: true)
        }
    }

    static func loadProfiles() -> [ProfileEntry] {
        try? ensureStorage()
        guard let dirs = try? FileManager.default.contentsOfDirectory(
            at: profilesRoot(),
            includingPropertiesForKeys: nil,
            options: [.skipsHiddenFiles]
        ) else { return [] }

        return dirs
            .filter { $0.hasDirectoryPath }
            .compactMap { try? loadProfile(named: $0.lastPathComponent) }
            .sorted { $0.name.localizedCaseInsensitiveCompare($1.name) == .orderedAscending }
    }

    static func loadProfile(named name: String) throws -> ProfileEntry {
        try ensureStorage()
        let url = profilesRoot().appendingPathComponent(name).appendingPathComponent("profile.yaml")
        guard FileManager.default.fileExists(atPath: url.path) else {
            throw NSError(domain: "SkillReader", code: 400, userInfo: [NSLocalizedDescriptionKey: "Profile not found: \(name)"])
        }
        let text = try String(contentsOf: url, encoding: .utf8)
        return try parseProfileYAML(text, url: url)
    }

    static func createProfile(name: String, description: String) throws -> ProfileEntry {
        let clean = try validateName(name)
        let dir = profilesRoot().appendingPathComponent(clean, isDirectory: true)
        if FileManager.default.fileExists(atPath: dir.path) {
            throw NSError(domain: "SkillReader", code: 401, userInfo: [NSLocalizedDescriptionKey: "Profile already exists: \(clean)"])
        }
        let profile = ProfileEntry(
            name: clean,
            description: description.trimmingCharacters(in: .whitespacesAndNewlines),
            assets: [],
            targets: Dictionary(uniqueKeysWithValues: profileTools.map { ($0, ProfileTarget()) }),
            profileURL: dir.appendingPathComponent("profile.yaml")
        )
        try saveProfile(profile)
        return profile
    }

    static func saveProfile(_ profile: ProfileEntry) throws {
        let dir = profile.profileURL.deletingLastPathComponent()
        try FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)
        try serializeProfileYAML(profile).write(to: profile.profileURL, atomically: true, encoding: .utf8)
    }

    static func deleteProfile(named name: String) throws {
        let dir = profilesRoot().appendingPathComponent(name, isDirectory: true)
        guard FileManager.default.fileExists(atPath: dir.path) else {
            throw NSError(domain: "SkillReader", code: 402, userInfo: [NSLocalizedDescriptionKey: "Profile not found: \(name)"])
        }
        try FileManager.default.removeItem(at: dir)
    }

    static func assetExists(kind: ProfileAssetKind, id: String) -> Bool {
        switch kind {
        case .skill:
            return FileManager.default.fileExists(atPath: libraryRoot().appendingPathComponent("skills/\(id)/SKILL.md").path)
        case .rule:
            let matches = (try? FileManager.default.contentsOfDirectory(
                at: libraryRoot().appendingPathComponent("rules", isDirectory: true),
                includingPropertiesForKeys: nil,
                options: [.skipsHiddenFiles]
            )) ?? []
            return matches.contains { $0.deletingPathExtension().lastPathComponent == id }
        case .agents:
            return FileManager.default.fileExists(atPath: libraryRoot().appendingPathComponent("agents/\(id).md").path)
        }
    }

    static func loadLibraryAssets(kind: ProfileAssetKind? = nil) -> [LibraryAssetEntry] {
        try? ensureStorage()
        let kinds = kind.map { [$0] } ?? ProfileAssetKind.allCases
        let assets = kinds.flatMap { loadLibraryAssets(for: $0) }
        return assets.sorted {
            if $0.kind != $1.kind {
                return $0.kind.rawValue < $1.kind.rawValue
            }
            return $0.assetID.localizedCaseInsensitiveCompare($1.assetID) == .orderedAscending
        }
    }

    static func importEntryToLibrary(_ entry: SkillEntry) throws -> LibraryAssetEntry {
        try ensureStorage()

        switch entry.entryType {
        case .skill:
            let destDir = libraryRoot().appendingPathComponent("skills/\(entry.assetID)", isDirectory: true)
            if !FileManager.default.fileExists(atPath: destDir.path) {
                try copyItemReplacingIfNeeded(from: entry.primaryPath, to: destDir)
            }

            let skillURL = destDir.appendingPathComponent("SKILL.md")
            let text = (try? String(contentsOf: skillURL, encoding: .utf8)) ?? ""
            let (metadata, body) = parseFrontmatter(text)
            return LibraryAssetEntry(
                kind: .skill,
                assetID: entry.assetID,
                title: metadata["name"] ?? entry.name,
                detail: metadata["description"] ?? firstMeaningfulLine(from: body),
                sourceURL: destDir,
                sourceKind: .library
            )

        case .rule:
            let ext = entry.primaryPath.pathExtension.isEmpty ? "md" : entry.primaryPath.pathExtension
            let destFile = libraryRoot().appendingPathComponent("rules/\(entry.assetID).\(ext)")
            if !FileManager.default.fileExists(atPath: destFile.path) {
                try copyItemReplacingIfNeeded(from: entry.primaryPath, to: destFile)
            }

            let text = (try? String(contentsOf: destFile, encoding: .utf8)) ?? ""
            let (metadata, body) = parseFrontmatter(text)
            return LibraryAssetEntry(
                kind: .rule,
                assetID: entry.assetID,
                title: metadata["name"] ?? entry.name,
                detail: metadata["description"] ?? firstMeaningfulLine(from: body),
                sourceURL: destFile,
                sourceKind: .library
            )
        }
    }

    static func addAsset(profileName: String, kind: ProfileAssetKind, assetID: String) throws -> ProfileEntry {
        var profile = try loadProfile(named: profileName)
        let cleanID = assetID.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !cleanID.isEmpty else {
            throw NSError(domain: "SkillReader", code: 403, userInfo: [NSLocalizedDescriptionKey: "Asset id cannot be empty."])
        }
        guard assetExists(kind: kind, id: cleanID) else {
            throw NSError(domain: "SkillReader", code: 404, userInfo: [NSLocalizedDescriptionKey: "Asset not found in library: \(cleanID)"])
        }
        let asset = ProfileAsset(kind: kind, assetID: cleanID)
        if !profile.assets.contains(asset) {
            profile.assets.append(asset)
            try saveProfile(profile)
        }
        return profile
    }

    static func removeAsset(profileName: String, kind: ProfileAssetKind, assetID: String) throws -> ProfileEntry {
        var profile = try loadProfile(named: profileName)
        profile.assets.removeAll { $0.kind == kind && $0.assetID == assetID }
        try saveProfile(profile)
        return profile
    }

    static func applyProfile(name: String, tool: String, cwd: URL) throws {
        let profile = try loadProfile(named: name)
        guard profileTools.contains(tool) else {
            throw NSError(domain: "SkillReader", code: 405, userInfo: [NSLocalizedDescriptionKey: "Unsupported tool: \(tool)"])
        }
        guard !profile.assets.isEmpty else {
            throw NSError(domain: "SkillReader", code: 406, userInfo: [NSLocalizedDescriptionKey: "Profile '\(name)' has no assets."])
        }

        let resolved = try profile.assets.map(resolveAsset)
        let manifestURL = manifestPath(cwd: cwd, profileName: name, tool: tool)
        if let manifest = try loadManifest(at: manifestURL) {
            try cleanup(manifest: manifest)
        }

        var manifest = ProfileManifest(profile_name: name, tool: tool, generated_paths: [], managed_files: [])
        switch tool {
        case "codex":
            try writeSkillAssets(baseDir: cwd.appendingPathComponent(".agents/skills", isDirectory: true), profileName: name, tool: tool, assets: resolved, manifest: &manifest)
            try upsertInstructionBlock(fileURL: cwd.appendingPathComponent("AGENTS.md"), profileName: name, tool: tool, body: renderSections(profile: profile, assets: resolved, includeSkills: false), manifest: &manifest)
        case "claude":
            try writeSkillAssets(baseDir: cwd.appendingPathComponent(".claude/skills", isDirectory: true), profileName: name, tool: tool, assets: resolved, manifest: &manifest)
            try upsertInstructionBlock(fileURL: cwd.appendingPathComponent("CLAUDE.md"), profileName: name, tool: tool, body: renderSections(profile: profile, assets: resolved, includeSkills: false), manifest: &manifest)
        case "windsurf":
            try writeSkillAssets(baseDir: cwd.appendingPathComponent(".windsurf/skills", isDirectory: true), profileName: name, tool: tool, assets: resolved, manifest: &manifest)
            try writeWindsurfRule(rulesDir: cwd.appendingPathComponent(".windsurf/rules", isDirectory: true), profileName: name, profile: profile, tool: tool, assets: resolved, manifest: &manifest)
        case "opencode":
            try writeSkillAssets(baseDir: cwd.appendingPathComponent(".opencode/skills", isDirectory: true), profileName: name, tool: tool, assets: resolved, manifest: &manifest)
            try upsertInstructionBlock(fileURL: cwd.appendingPathComponent("AGENTS.md"), profileName: name, tool: tool, body: renderSections(profile: profile, assets: resolved, includeSkills: false), manifest: &manifest)
        default:
            try writeCursorRule(rulesDir: cwd.appendingPathComponent(".cursor/rules", isDirectory: true), profileName: name, profile: profile, tool: tool, assets: resolved, manifest: &manifest)
        }
        try saveManifest(manifest, at: manifestURL)
    }

    static func previewApplication(name: String, tool: String, cwd: URL) throws -> ProfileApplicationPreview {
        let profile = try loadProfile(named: name)
        guard profileTools.contains(tool) else {
            throw NSError(domain: "SkillReader", code: 409, userInfo: [NSLocalizedDescriptionKey: "Unsupported tool: \(tool)"])
        }
        guard !profile.assets.isEmpty else {
            throw NSError(domain: "SkillReader", code: 410, userInfo: [NSLocalizedDescriptionKey: "Profile '\(name)' has no assets."])
        }

        let resolved = try profile.assets.map(resolveAsset)
        let plan = plannedWrites(profileName: name, profile: profile, tool: tool, cwd: cwd, assets: resolved)

        return ProfileApplicationPreview(
            profileName: name,
            tool: tool,
            cwd: cwd,
            assets: resolved.map {
                ProfilePreviewAsset(
                    kind: $0.kind,
                    assetID: $0.assetID,
                    title: $0.title,
                    description: $0.description
                )
            },
            generatedPaths: plan.generated,
            managedFiles: plan.managed
        )
    }

    // MARK: - YAML

    private static func parseProfileYAML(_ text: String, url: URL) throws -> ProfileEntry {
        var name = ""
        var description = ""
        var assets: [ProfileAsset] = []
        var targets: [String: ProfileTarget] = [:]
        var currentSection = ""
        var currentAssetKind: String?
        var currentTargetTool: String?

        for rawLine in text.components(separatedBy: .newlines) {
            if rawLine.trimmingCharacters(in: .whitespaces).isEmpty { continue }
            let line = rawLine
            let trimmed = line.trimmingCharacters(in: .whitespaces)
            if line.hasPrefix("name:") {
                name = String(line.dropFirst("name:".count)).trimmingCharacters(in: .whitespaces)
            } else if line.hasPrefix("description:") {
                description = String(line.dropFirst("description:".count)).trimmingCharacters(in: .whitespaces)
            } else if trimmed == "assets:" {
                currentSection = "assets"
            } else if trimmed == "targets:" {
                currentSection = "targets"
            } else if currentSection == "assets" && trimmed.hasPrefix("- kind:") {
                currentAssetKind = String(trimmed.dropFirst("- kind:".count)).trimmingCharacters(in: .whitespaces)
            } else if currentSection == "assets" && trimmed.hasPrefix("id:") {
                let assetID = String(trimmed.dropFirst("id:".count)).trimmingCharacters(in: .whitespaces)
                if let currentAssetKind, let kind = ProfileAssetKind(rawValue: currentAssetKind) {
                    assets.append(ProfileAsset(kind: kind, assetID: assetID))
                }
                currentAssetKind = nil
            } else if currentSection == "targets" && trimmed.hasSuffix(":") && !trimmed.hasPrefix("mode") {
                currentTargetTool = String(trimmed.dropLast())
            } else if currentSection == "targets" && trimmed.hasPrefix("mode:") {
                let mode = String(trimmed.dropFirst("mode:".count)).trimmingCharacters(in: .whitespaces)
                if let currentTargetTool {
                    targets[currentTargetTool] = ProfileTarget(mode: mode)
                }
                currentTargetTool = nil
            }
        }

        guard !name.isEmpty else {
            throw NSError(domain: "SkillReader", code: 407, userInfo: [NSLocalizedDescriptionKey: "Invalid profile.yaml: missing name"])
        }
        return ProfileEntry(name: name, description: description, assets: assets, targets: targets, profileURL: url)
    }

    private static func serializeProfileYAML(_ profile: ProfileEntry) -> String {
        var lines = [
            "name: \(profile.name)",
            "description: \(profile.description)",
            "assets:"
        ]
        if profile.assets.isEmpty {
            lines.append("[]")
        } else {
            for asset in profile.assets {
                lines.append("  - kind: \(asset.kind.rawValue)")
                lines.append("    id: \(asset.assetID)")
            }
        }
        lines.append("targets:")
        for tool in profile.targets.keys.sorted() {
            let target = profile.targets[tool] ?? ProfileTarget()
            lines.append("  \(tool):")
            lines.append("    mode: \(target.mode)")
        }
        return lines.joined(separator: "\n") + "\n"
    }

    // MARK: - Asset resolution

    private struct ResolvedAsset {
        var kind: ProfileAssetKind
        var assetID: String
        var sourceURL: URL
        var title: String
        var description: String
        var body: String
    }

    private static func resolveAsset(_ asset: ProfileAsset) throws -> ResolvedAsset {
        switch asset.kind {
        case .skill:
            let dir = libraryRoot().appendingPathComponent("skills/\(asset.assetID)", isDirectory: true)
            let skillURL = dir.appendingPathComponent("SKILL.md")
            let text = try String(contentsOf: skillURL, encoding: .utf8)
            let (metadata, body) = parseFrontmatter(text)
            return ResolvedAsset(
                kind: .skill,
                assetID: asset.assetID,
                sourceURL: dir,
                title: metadata["name"] ?? asset.assetID,
                description: metadata["description"] ?? "",
                body: body.trimmingCharacters(in: .whitespacesAndNewlines)
            )
        case .rule:
            let rulesDir = libraryRoot().appendingPathComponent("rules", isDirectory: true)
            let files = try FileManager.default.contentsOfDirectory(at: rulesDir, includingPropertiesForKeys: nil, options: [.skipsHiddenFiles])
            guard let match = files.first(where: { $0.deletingPathExtension().lastPathComponent == asset.assetID }) else {
                throw NSError(domain: "SkillReader", code: 408, userInfo: [NSLocalizedDescriptionKey: "Rule asset not found: \(asset.assetID)"])
            }
            let text = try String(contentsOf: match, encoding: .utf8)
            let (metadata, body) = parseFrontmatter(text)
            return ResolvedAsset(
                kind: .rule,
                assetID: asset.assetID,
                sourceURL: match,
                title: metadata["name"] ?? match.deletingPathExtension().lastPathComponent,
                description: metadata["description"] ?? "",
                body: body.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty ? text.trimmingCharacters(in: .whitespacesAndNewlines) : body.trimmingCharacters(in: .whitespacesAndNewlines)
            )
        case .agents:
            let file = libraryRoot().appendingPathComponent("agents/\(asset.assetID).md")
            let text = try String(contentsOf: file, encoding: .utf8)
            return ResolvedAsset(kind: .agents, assetID: asset.assetID, sourceURL: file, title: asset.assetID, description: "", body: text.trimmingCharacters(in: .whitespacesAndNewlines))
        }
    }

    private static func loadLibraryAssets(for kind: ProfileAssetKind) -> [LibraryAssetEntry] {
        switch kind {
        case .skill:
            let dir = libraryRoot().appendingPathComponent("skills", isDirectory: true)
            let items = (try? FileManager.default.contentsOfDirectory(at: dir, includingPropertiesForKeys: nil, options: [.skipsHiddenFiles])) ?? []
            return items.compactMap { item in
                guard item.hasDirectoryPath else { return nil }
                let skillURL = item.appendingPathComponent("SKILL.md")
                guard FileManager.default.fileExists(atPath: skillURL.path) else { return nil }
                let text = (try? String(contentsOf: skillURL, encoding: .utf8)) ?? ""
                let (metadata, body) = parseFrontmatter(text)
                let detail = metadata["description"] ?? firstMeaningfulLine(from: body)
                return LibraryAssetEntry(
                    kind: .skill,
                    assetID: item.lastPathComponent,
                    title: metadata["name"] ?? item.lastPathComponent,
                    detail: detail,
                    sourceURL: item
                )
            }
        case .rule:
            let dir = libraryRoot().appendingPathComponent("rules", isDirectory: true)
            let items = (try? FileManager.default.contentsOfDirectory(at: dir, includingPropertiesForKeys: nil, options: [.skipsHiddenFiles])) ?? []
            return items.filter { !$0.hasDirectoryPath }.map { item in
                let text = (try? String(contentsOf: item, encoding: .utf8)) ?? ""
                let (metadata, body) = parseFrontmatter(text)
                return LibraryAssetEntry(
                    kind: .rule,
                    assetID: item.deletingPathExtension().lastPathComponent,
                    title: metadata["name"] ?? item.deletingPathExtension().lastPathComponent,
                    detail: metadata["description"] ?? firstMeaningfulLine(from: body),
                    sourceURL: item
                )
            }
        case .agents:
            let dir = libraryRoot().appendingPathComponent("agents", isDirectory: true)
            let items = (try? FileManager.default.contentsOfDirectory(at: dir, includingPropertiesForKeys: nil, options: [.skipsHiddenFiles])) ?? []
            return items.filter { !$0.hasDirectoryPath && $0.pathExtension.lowercased() == "md" }.map { item in
                let text = (try? String(contentsOf: item, encoding: .utf8)) ?? ""
                return LibraryAssetEntry(
                    kind: .agents,
                    assetID: item.deletingPathExtension().lastPathComponent,
                    title: item.deletingPathExtension().lastPathComponent,
                    detail: firstMeaningfulLine(from: text),
                    sourceURL: item
                )
            }
        }
    }

    private static func parseFrontmatter(_ text: String) -> ([String: String], String) {
        guard text.hasPrefix("---\n") else { return ([:], text) }
        let parts = text.components(separatedBy: "\n---\n")
        guard parts.count >= 2 else { return ([:], text) }
        var metadata: [String: String] = [:]
        let header = parts[0].replacingOccurrences(of: "---\n", with: "")
        for line in header.components(separatedBy: .newlines) {
            let split = line.split(separator: ":", maxSplits: 1).map(String.init)
            if split.count == 2 {
                metadata[split[0].trimmingCharacters(in: .whitespaces)] = split[1].trimmingCharacters(in: .whitespaces)
            }
        }
        let body = parts.dropFirst().joined(separator: "\n---\n")
        return (metadata, body)
    }

    private static func firstMeaningfulLine(from text: String) -> String {
        text
            .components(separatedBy: .newlines)
            .map { $0.trimmingCharacters(in: .whitespacesAndNewlines) }
            .first { !$0.isEmpty && !$0.hasPrefix("#") && !$0.hasPrefix("---") } ?? ""
    }

    private static func copyItemReplacingIfNeeded(from source: URL, to destination: URL) throws {
        if FileManager.default.fileExists(atPath: destination.path) {
            try FileManager.default.removeItem(at: destination)
        }
        try FileManager.default.createDirectory(at: destination.deletingLastPathComponent(), withIntermediateDirectories: true)
        try FileManager.default.copyItem(at: source, to: destination)
    }

    // MARK: - Materialization

    private static func writeSkillAssets(baseDir: URL, profileName: String, tool: String, assets: [ResolvedAsset], manifest: inout ProfileManifest) throws {
        try FileManager.default.createDirectory(at: baseDir, withIntermediateDirectories: true)
        for asset in assets where asset.kind == .skill {
            let dest = baseDir.appendingPathComponent(asset.assetID, isDirectory: true)
            if FileManager.default.fileExists(atPath: dest.path) {
                try FileManager.default.removeItem(at: dest)
            }
            try copyDirectory(from: asset.sourceURL, to: dest)
            let skillURL = dest.appendingPathComponent("SKILL.md")
            if FileManager.default.fileExists(atPath: skillURL.path) {
                let original = try String(contentsOf: skillURL, encoding: .utf8)
                try (generatedComment(profileName: profileName, tool: tool) + "\n\n" + original).write(to: skillURL, atomically: true, encoding: .utf8)
            }
            manifest.generated_paths.append(dest.path)
        }
    }

    private static func writeCursorRule(rulesDir: URL, profileName: String, profile: ProfileEntry, tool: String, assets: [ResolvedAsset], manifest: inout ProfileManifest) throws {
        try FileManager.default.createDirectory(at: rulesDir, withIntermediateDirectories: true)
        let file = rulesDir.appendingPathComponent("profile-\(profileName).mdc")
        let content = [
            "---",
            "description: Materialized profile \(profileName)",
            "alwaysApply: true",
            "---",
            "",
            generatedComment(profileName: profileName, tool: tool),
            "",
            renderSections(profile: profile, assets: assets, includeSkills: true),
            ""
        ].joined(separator: "\n")
        try content.write(to: file, atomically: true, encoding: .utf8)
        manifest.generated_paths.append(file.path)
    }

    private static func writeWindsurfRule(rulesDir: URL, profileName: String, profile: ProfileEntry, tool: String, assets: [ResolvedAsset], manifest: inout ProfileManifest) throws {
        try FileManager.default.createDirectory(at: rulesDir, withIntermediateDirectories: true)
        let file = rulesDir.appendingPathComponent("profile-\(profileName).md")
        let content = [
            "---",
            "trigger: always_on",
            "---",
            "",
            generatedComment(profileName: profileName, tool: tool),
            "",
            renderSections(profile: profile, assets: assets, includeSkills: false),
            ""
        ].joined(separator: "\n")
        try content.write(to: file, atomically: true, encoding: .utf8)
        manifest.generated_paths.append(file.path)
    }

    private static func upsertInstructionBlock(fileURL: URL, profileName: String, tool: String, body: String, manifest: inout ProfileManifest) throws {
        let blockID = blockID(profileName: profileName, tool: tool)
        let block = [
            blockStart(blockID),
            generatedComment(profileName: profileName, tool: tool),
            "",
            body,
            blockEnd(blockID)
        ].joined(separator: "\n")

        let existing = (try? String(contentsOf: fileURL, encoding: .utf8)) ?? ""
        let updated = replaceOrAppendBlock(existing, blockID: blockID, block: block)
        try FileManager.default.createDirectory(at: fileURL.deletingLastPathComponent(), withIntermediateDirectories: true)
        try updated.write(to: fileURL, atomically: true, encoding: .utf8)
        manifest.managed_files.append(fileURL.path)
    }

    private static func replaceOrAppendBlock(_ text: String, blockID: String, block: String) -> String {
        let start = blockStart(blockID)
        let end = blockEnd(blockID)
        if let startRange = text.range(of: start), let endRange = text.range(of: end) {
            let replaceRange = startRange.lowerBound..<endRange.upperBound
            var updated = text
            updated.replaceSubrange(replaceRange, with: block)
            return updated.trimmingCharacters(in: .whitespacesAndNewlines) + "\n"
        }
        if text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            return block + "\n"
        }
        return text.trimmingCharacters(in: .whitespacesAndNewlines) + "\n\n" + block + "\n"
    }

    private static func renderSections(profile: ProfileEntry, assets: [ResolvedAsset], includeSkills: Bool) -> String {
        var sections = ["# Profile: \(profile.name)"]
        if !profile.description.isEmpty { sections.append(profile.description) }
        for asset in assets {
            if asset.kind == .skill && !includeSkills { continue }
            sections.append("## \(asset.kind.rawValue.capitalized): \(asset.title)")
            if asset.kind == .skill && !asset.description.isEmpty {
                sections.append(asset.description + "\n\n" + asset.body)
            } else {
                sections.append(asset.body)
            }
        }
        return sections.filter { !$0.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty }.joined(separator: "\n\n")
    }

    // MARK: - Manifest / cleanup

    private static func plannedWrites(profileName: String, profile: ProfileEntry, tool: String, cwd: URL, assets: [ResolvedAsset]) -> (generated: [URL], managed: [URL]) {
        let generatedSkills: [URL]
        let managedFiles: [URL]

        switch tool {
        case "codex":
            generatedSkills = plannedSkillDestinations(baseDir: cwd.appendingPathComponent(".agents/skills", isDirectory: true), assets: assets)
            managedFiles = [cwd.appendingPathComponent("AGENTS.md")]
        case "claude":
            generatedSkills = plannedSkillDestinations(baseDir: cwd.appendingPathComponent(".claude/skills", isDirectory: true), assets: assets)
            managedFiles = [cwd.appendingPathComponent("CLAUDE.md")]
        case "windsurf":
            generatedSkills = plannedSkillDestinations(baseDir: cwd.appendingPathComponent(".windsurf/skills", isDirectory: true), assets: assets)
            managedFiles = [cwd.appendingPathComponent(".windsurf/rules/profile-\(profileName).md")]
        case "opencode":
            generatedSkills = plannedSkillDestinations(baseDir: cwd.appendingPathComponent(".opencode/skills", isDirectory: true), assets: assets)
            managedFiles = [cwd.appendingPathComponent("AGENTS.md")]
        default:
            generatedSkills = [cwd.appendingPathComponent(".cursor/rules/profile-\(profile.name).mdc")]
            managedFiles = []
        }

        return (generatedSkills, managedFiles)
    }

    private static func plannedSkillDestinations(baseDir: URL, assets: [ResolvedAsset]) -> [URL] {
        assets
            .filter { $0.kind == .skill }
            .map { baseDir.appendingPathComponent($0.assetID, isDirectory: true) }
    }

    private static func manifestPath(cwd: URL, profileName: String, tool: String) -> URL {
        cwd.appendingPathComponent(".skill-reader/applied-profiles/\(tool)--\(profileName).json")
    }

    private static func loadManifest(at url: URL) throws -> ProfileManifest? {
        guard FileManager.default.fileExists(atPath: url.path) else { return nil }
        let data = try Data(contentsOf: url)
        return try JSONDecoder().decode(ProfileManifest.self, from: data)
    }

    private static func saveManifest(_ manifest: ProfileManifest, at url: URL) throws {
        try FileManager.default.createDirectory(at: url.deletingLastPathComponent(), withIntermediateDirectories: true)
        let data = try JSONEncoder().encode(manifest)
        try data.write(to: url)
    }

    private static func cleanup(manifest: ProfileManifest) throws {
        for raw in manifest.generated_paths {
            let url = URL(fileURLWithPath: raw)
            if url.hasDirectoryPath {
                try? FileManager.default.removeItem(at: url)
            } else if FileManager.default.fileExists(atPath: url.path) {
                try? FileManager.default.removeItem(at: url)
            }
        }
        for raw in manifest.managed_files {
            let url = URL(fileURLWithPath: raw)
            guard FileManager.default.fileExists(atPath: url.path) else { continue }
            let text = try String(contentsOf: url, encoding: .utf8)
            let cleaned = removeBlock(text, blockID: blockID(profileName: manifest.profile_name, tool: manifest.tool))
            if cleaned.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
                try? FileManager.default.removeItem(at: url)
            } else {
                try cleaned.trimmingCharacters(in: .whitespacesAndNewlines).appending("\n").write(to: url, atomically: true, encoding: .utf8)
            }
        }
    }

    private static func removeBlock(_ text: String, blockID: String) -> String {
        let start = blockStart(blockID)
        let end = blockEnd(blockID)
        guard let startRange = text.range(of: start), let endRange = text.range(of: end) else { return text }
        var updated = text
        updated.removeSubrange(startRange.lowerBound..<endRange.upperBound)
        return updated
    }

    // MARK: - Helpers

    private static func generatedComment(profileName: String, tool: String) -> String {
        "<!-- \(generatedPrefix): \(profileName) (\(tool)) -->"
    }

    private static func blockID(profileName: String, tool: String) -> String {
        "profile=\(profileName);tool=\(tool)"
    }

    private static func blockStart(_ blockID: String) -> String {
        "<!-- skill-reader:begin \(blockID) -->"
    }

    private static func blockEnd(_ blockID: String) -> String {
        "<!-- skill-reader:end \(blockID) -->"
    }

    private static func validateName(_ name: String) throws -> String {
        let clean = name.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !clean.isEmpty else {
            throw NSError(domain: "SkillReader", code: 409, userInfo: [NSLocalizedDescriptionKey: "Name cannot be empty."])
        }
        let invalid = CharacterSet.alphanumerics.union(CharacterSet(charactersIn: "-_")).inverted
        if clean.rangeOfCharacter(from: invalid) != nil {
            throw NSError(domain: "SkillReader", code: 410, userInfo: [NSLocalizedDescriptionKey: "Use only letters, numbers, '-' and '_' in the name."])
        }
        return clean
    }

    private static func copyDirectory(from source: URL, to destination: URL) throws {
        try FileManager.default.createDirectory(at: destination.deletingLastPathComponent(), withIntermediateDirectories: true)
        try FileManager.default.copyItem(at: source, to: destination)
    }
}
